# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21e928e2a19b8cd8c9bb2994958f670e20802b6162c974f360cad6483ff5aa2892a363204209ae689721ed10d7c89ec50693933ad4d0966b0cf13cb29d1f3d01

test:
  secret_key_base: d365f2ca136637561382de19d7aeb4339b5e6262436f66b8615ea474b330a2bca6f3724ca28be11d2ae512a8b8d175a297c00d1b1876e35d65df54ca2ffbd234

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
